# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
  working_directory: ~/code
    docker:      
      - image: circleci/android:api-28 
    environment:    
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout      
      - restore_cache:
          keys:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}            
            - v1-dependencies-
      - save_cache:          
            paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build assembleRelease
          command: ./gradlew assembleRelease
      - run:
          name: Build assembleRelease
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      

   
